// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)


#include "can_bus.h"
#include "MotorCAN_can_msgs.h"


/* CAN_RECV_ENTRY(0x401, CAN_DLC_MC_DRIVECOMMAND, true)
CAN_RECV_ENTRY(0x402, CAN_DLC_MC_POWERCOMMAND, true)
CAN_RECV_ENTRY(0x403, CAN_DLC_MC_RESETCOMMAND, true)

CAN_RECV_ENTRY(0x420, CAN_DLC_MC_INFO, true)

*/
CAN_RECV_ENTRY(0x421, CAN_DLC_MC_STATUS, true)

/*
CAN_RECV_ENTRY(0x422, CAN_DLC_MC_BUSMEASUREMENT, true)
CAN_RECV_ENTRY(0x423, CAN_DLC_MC_VELOCITYMEASUREMENT, true)
CAN_RECV_ENTRY(0x424, CAN_DLC_MC_PHASECURRENTMEASUREMENT, true)
CAN_RECV_ENTRY(0x425, CAN_DLC_MC_MOTORVOLTAGEVECTORMEASUREMENT, true)
CAN_RECV_ENTRY(0x426, CAN_DLC_MC_MOTORCURRENTVECTORMEASUREMENT, true)
CAN_RECV_ENTRY(0x427, CAN_DLC_MC_BACKEMFMEASUREMENTPREDICTION, true)
CAN_RECV_ENTRY(0x428, CAN_DLC_MC_15VRAILMEASUREMENT, true)
CAN_RECV_ENTRY(0x429, CAN_DLC_MC_3V319VRAILMEASUREMENT, true)
*/
CAN_RECV_ENTRY(0x42B, CAN_DLC_MC_MOTOR_TEMPMEASUREMENT, true)
/*
CAN_RECV_ENTRY(0x42C, CAN_DLC_MC_DSPBOARDTEMPMEASUREMENT, true)
CAN_RECV_ENTRY(0x42E, CAN_DLC_MC_ODOMETERBUSAHMEASUREMENT, true)
CAN_RECV_ENTRY(0x437, CAN_DLC_MC_SLIPSPEEDMEASUREMENT, true)
*/

// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)

// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)

// CAN_RECV_ENTRY(0x2, 8, false)
// CAN_RECV_ENTRY(CAN_ID_MC_STATUS, CAN_DLC_MC_STATUS, true)

//CAN_RECV_ENTRY(0x002, 8, true)