// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)


#include "can_bus.h"
#include "MotorCAN_can_msgs.h"

CAN_RECV_ENTRY(CAN_DLC_MC_STATUS, CAN_DLC_MC_STATUS, true)
CAN_RECV_ENTRY(CAN_DLC_MC_MOTOR_TEMPMEASUREMENT, CAN_DLC_MC_MOTOR_TEMPMEASUREMENT, true)
