//configures PWM1, PWM2, and LED ports

#pragma once
#define PINDEFS_H

// ===== PWM1 CONFIGURATION (PA2 - TIM2 Channel 3) =====
#define PWM1_TIMER_INSTANCE TIM2
#define PWM1_TIMER_CHANNEL TIM_CHANNEL_3

#define PWM1_GPIO_PORT GPIOA
#define PWM1_GPIO_PIN GPIO_PIN_2
#define PWM1_GPIO_AF GPIO_AF1_TIM2

#define PWM1_TIMER_CLK_ENABLE() __HAL_RCC_TIM2_CLK_ENABLE()
#define PWM1_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()

// ===== PWM2 CONFIGURATION (PA5 - TIM2 Channel 1) =====
#define PWM2_TIMER_INSTANCE TIM2
#define PWM2_TIMER_CHANNEL TIM_CHANNEL_1

#define PWM2_GPIO_PORT GPIOA
#define PWM2_GPIO_PIN GPIO_PIN_5
#define PWM2_GPIO_AF GPIO_AF1_TIM2

#define PWM2_TIMER_CLK_ENABLE() __HAL_RCC_TIM2_CLK_ENABLE()
#define PWM2_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()

// ===== LED CONFIGURATION =====
#define LED_PIN GPIO_PIN_0
#define LED_PORT GPIOB
